services:
  db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: welcome
      MYSQL_DATABASE: demo
      MYSQL_USER: user1
      MYSQL_PASSWORD: welcome
    ports:
      - "3309:3306"
    networks:
      - springboot-mysql-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 3s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql
    command: [ mysqld, --mysql-native-password=ON ]
  app:
    build:
      dockerfile: Dockerfile
    container_name: springboot_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/demo?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: user1
      SPRING_DATASOURCE_PASSWORD: welcome
      SPRING_FLYWAY_ENABLED: true
    ports:
      - "8080:8080"
    networks:
      - springboot-mysql-network

networks:
  springboot-mysql-network:
    driver: bridge

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./local-mysql-data

# Note: If your application is not starting properly due to MySQL errors,
# then please delete the local-mysql-data folder and then try again from scratch.